version: "3.9"

services:
  nginx:
    image: nginx
    build:
      context: ./api-gateway/
    ports:
      - "3000:80"
    depends_on:
      - auth
    networks:
      - public-network
      - secure-network
      - auth-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

  auth:
    image: auth
    build:
      context: ./auth-server/
    env_file:
      - ./auth-server/.env
    depends_on:
      - postgres
      - redis
    networks:
      - public-network
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s


  secure:
    image: secure
    build:
      context: ./secure-server/
    networks:
      - secure-network
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s

  postgres:
    image: postgres
    build:
      context: ./auth-server/database/
    container_name: postgres
    restart: "on-failure"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - public-network

  redis:
    image: redis:6.2
    container_name: redis
    restart: "on-failure"
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
    networks:
      - public-network

networks:
  public-network:
    driver: bridge
    internal: false
  secure-network:
    driver: bridge
    internal: true
  auth-network:
    driver: bridge
    internal: true

volumes:
  pg_data:
  redis:
